// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGAKrsGkhFpOdFkt-d7B6Se1-4sEXRx98',
    appId: '1:1082401659689:web:24364529aa162dea157538',
    messagingSenderId: '1082401659689',
    projectId: 'cdhsappllication',
    authDomain: 'cdhsappllication.firebaseapp.com',
    storageBucket: 'cdhsappllication.firebasestorage.app',
    measurementId: 'G-5R21PFRZC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS6wwQIANyG2K88ZtllOkgPmonAAyam8I',
    appId: '1:1082401659689:android:7304fa2f87e8f267157538',
    messagingSenderId: '1082401659689',
    projectId: 'cdhsappllication',
    storageBucket: 'cdhsappllication.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjFgNk3P8HCEV9IwZWUo6jRh8KjbIac4I',
    appId: '1:1082401659689:ios:ca3d3fc86a822f88157538',
    messagingSenderId: '1082401659689',
    projectId: 'cdhsappllication',
    storageBucket: 'cdhsappllication.firebasestorage.app',
    iosBundleId: 'com.example.cdhsApp',
  );
}
